# Generated by Django 6.0.3 on 2026-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_access_id', models.CharField(help_text='Unique identifier from access control device', max_length=50)),
                ('account_user_id', models.CharField(max_length=50, null=True)),
                ('accounting_system', models.CharField(help_text='Accounting system name', max_length=50)),
                ('access_status', models.CharField(choices=[('grant', 'Grant'), ('reject', 'Reject')], max_length=10)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_access_id', models.CharField(blank=True, help_text='Unique identifier from access control device', max_length=50, null=True, unique=True)),
                ('account_user_id', models.CharField(help_text='Unique identifier from accounting system', max_length=50, unique=True)),
                ('accounting_system', models.CharField(choices=[('palladium', 'Palladium'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero')], default='palladium', help_text='Accounting system name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappingModalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PendingAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_access_id', models.CharField(help_text='Unique identifier from access control device', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
