# Generated by Django 6.0.3 on 2026-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(help_text='Unique identifier from access control device', max_length=50, unique=True)),
                ('mapping_id', models.CharField(help_text='Unique identifier from accounting system', max_length=50, unique=True)),
                ('mapping_system', models.CharField(help_text='Accounting system name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TempMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(help_text='Unique identifier from access control device', max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
