# Generated by Django 6.0.3 on 2026-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(help_text='Unique identifier from access control device', max_length=50)),
                ('mapping_id', models.CharField(max_length=50, null=True)),
                ('mapping_system', models.CharField(help_text='Accounting system name', max_length=50)),
                ('status', models.CharField(choices=[('grant', 'Grant'), ('reject', 'Reject')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=10)),
            ],
        ),
    ]
