# Generated by Django 6.0.3 on 2026-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaccountmapping',
            name='device_access_id',
            field=models.CharField(blank=True, help_text='Unique identifier from access control device', max_length=50, null=True, unique=True),
        ),
    ]
