# Generated by Django 6.0.3 on 2026-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_accesslog_modalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='access_id',
            field=models.CharField(blank=True, help_text='Unique identifier from access control device', max_length=50, null=True, unique=True),
        ),
    ]
