# Generated by Django 6.0.3 on 2026-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_pendingaccountmapping_device_access_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('allow_all', 'Allow All'), ('reject_all', 'Reject All'), ('balance_threshold', 'Balance Threshold')], max_length=50, unique=True)),
                ('value', models.CharField(help_text='Value for the setting (e.g. true/false for allow_all and reject_all, numeric value for balance_threshold)', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Description of the setting', null=True)),
            ],
        ),
    ]
