# Generated by Django 6.0.3 on 2026-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='value',
        ),
        migrations.AddField(
            model_name='setting',
            name='authorization_flow',
            field=models.CharField(choices=[('grant_all', 'Grant All'), ('reject_all', 'Reject All'), ('check_balance', 'Check Balance')], default='check_balance', help_text='Authorization flow to determine access decisions', max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='balance_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum balance required for access', max_digits=10, null=True),
        ),
    ]
