# Generated by Django 6.0.3 on 2026-03-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_remove_setting_description_remove_setting_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesseventlog',
            name='account_user_id',
        ),
        migrations.RemoveField(
            model_name='accesseventlog',
            name='accounting_system',
        ),
        migrations.AddField(
            model_name='accesseventlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked account mapping if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.accountmapping'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='first_name',
            field=models.CharField(blank=True, help_text="User's first name", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='last_name',
            field=models.CharField(blank=True, help_text="User's last name", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='usd_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's balance in USD", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='zwg_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's balance in ZWG", max_digits=10, null=True),
        ),
    ]
