# Generated by Django 6.0.3 on 2026-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_remove_accesseventlog_account_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmapping',
            options={'ordering': ['-last_name', '-first_name']},
        ),
        migrations.AddField(
            model_name='setting',
            name='usd_balance_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum USD balance required for access', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='zwg_balance_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum ZWG balance required for access', max_digits=10, null=True),
        ),
    ]
