# Generated by Django 6.0.3 on 2026-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_remove_setting_balance_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='authorization_flow',
            field=models.CharField(choices=[('grant_all', 'Grant All'), ('reject_all', 'Reject All'), ('check_usd_balance', 'Check USD Balance'), ('check_zwg_balance', 'Check ZWG Balance'), ('check_usd_or_zwg_balance', 'Check USD or ZWG Balance')], default='check_usd_balance', help_text='Authorization flow to determine access decisions', max_length=30),
        ),
    ]
