# Generated by Django 6.0.3 on 2026-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_alter_setting_authorization_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmapping',
            name='narration',
            field=models.CharField(blank=True, help_text="User's description/narration from accounting system", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='authorization_flow',
            field=models.CharField(choices=[('grant_all', 'Grant All'), ('reject_all', 'Reject All'), ('check_usd_balance', 'Check USD Balance'), ('check_zwg_balance', 'Check ZWG Balance'), ('check_usd_or_zwg_balance', 'Check USD/ZWG Balance')], default='check_usd_balance', help_text='Authorization flow to determine access decisions', max_length=30),
        ),
    ]
